name: Bug
description: Report a bug, request fixes or improvements.
title: "[BUG] "
labels:
  - bug
body:
  # 你做了什么？
  - type: textarea
    id: what-you-did
    attributes:
      label: What you did?
      # 打开什么页面，做了什么操作，请使用列表，分步描述。
      description: What page you opened, what operation you did, please use a list to describe step by step.
      placeholder: >
        1. Opened the page of ...
        2. Clicked the button of ...
        3. ...
  # 你期望发生什么？
  - type: textarea
    id: what-you-expected
    attributes:
      label: What you expected?
      # 你期望发生什么？请使用列表，分步描述。
      description: What you expected? Please use a list to describe step by step.
      placeholder: >
        1. The page should ...
        2. The button should ...
        3. ...
  # 你看到了什么？
  - type: textarea
    id: what-you-saw
    attributes:
      label: What you saw?
      # 你看到了什么？请使用列表，分步描述。
      description: What you saw? Please use a list to describe step by step.
      placeholder: >
        1. The page ...
        2. The button ...
        3. ...
  # 修复建议
  - type: textarea
    id: fix-suggestion
    attributes:
      label: Fix Suggestion
      # 你认为应该如何修复？请使用列表，分步描述。
      description: How do you think it should be fixed? Please use a list to describe step by step.
      placeholder: >
        1. The page should ...
        2. The button should ...
        3. ...